### ISSUE TITLE
Switch from !… to (…) for bookmarklet source code

### ISSUE THREAD

**Issue by simevidas** [edenspiekermann/outline-audit#2]
For some reason, Firefox does not support this style of writing bookmarklets (the page is destroyed when activating the bookmarklet):

``` html
<a href="javascript:!function(…){…}(…);">
```

Could you switch to this style in the README and in the blog post:

``` html
<a href="javascript:(function(…){…}(…));">
```

**Comment by KittyGiraudel** [comment]
Done, thanks. :)
